
<div class="items">
                <div class="item">
                        <h3>LOREM IPSUM DOLOR</h3>
                        <img src="<?php echo PUBLIC_URL;?>/images/item1.jpg" alt="" width="85" height="148" />
                        <p>
                                Lorem ipsum dolor amet wisi enim. 
                                <span>$ 14,00</span>
                                <a href="#" class="red">Details</a>
                                <a href="#">Add to cart</a>
                        </p>
                </div>
                <div class="item">
                        <h3>IPSUM DOLOR</h3>
                        <img src="<?php echo PUBLIC_URL;?>/images/item2.jpg" alt="" width="85" height="148" />
                        <p>
                                Ipsum dolor amet wisi enim minim. 
                                <span>$ 15,00</span>
                                <a href="#" class="red">Details</a>
                                <a href="#">Add to cart</a>
                        </p>
                </div>
                <div class="item">
                        <h3>AMET WISI ENIM</h3>
                        <img src="<?php echo PUBLIC_URL;?>/images/item3.jpg" alt="" width="85" height="148" />
                        <p>
                                Amet wisi enim minim veniam quis. 
                                <span>$ 16,00</span>
                                <a href="#" class="red">Details</a>
                                <a href="#">Add to cart</a>
                        </p>
                </div>
                <div class="item">
                        <h3>DOLOR AMET WISI</h3>
                        <img src="<?php echo PUBLIC_URL;?>/images/item4.jpg" alt="" width="85" height="148" />
                        <p>
                                Dolor amet wisi enim ad minim.
                                <span>$ 28,00</span>
                                <a href="#" class="red">Details</a>
                                <a href="#">Add to cart</a>
                        </p>
                </div>
</div>