<?php
    function createData(){
        $courseData = array(
						array('name' => 'Build web responsive with Bootstrap'	, 'image' => 'bootstrap.jpg'	, 'description' => 'Ä�Ã¢y lÃ  má»™t trong nhá»¯ng CSS framework lá»›n nháº¥t vÃ  thÃ´ng dá»¥ng nháº¥t hiá»‡n nay. Bootstrap framework sáº½ giÃºp cÃ¡c báº¡n xÃ¢y dá»±ng nhanh giao diá»‡n web theo Ä‘Ãºng chuáº©n cá»§a w3C vÃ  ngoÃ i ra há»— trá»£ báº¡n lÃ m web trÃªn má»�i thiáº¿t bá»‹ khÃ¡c nhau nhÆ° laptop, tablet, smartphone (web responsive'),
						array('name' => 'Build web responsive with Dreamview'		, 'image' => 'html.jpg'			, 'description' => 'NhÆ° chÃºng ta Ä‘Ã£ biáº¿t website Ä‘Ã£ trá»Ÿ thÃ nh má»™t thÃ nh pháº§n khÃ´ng thá»ƒ thiáº¿u cá»§a thá»�i Ä‘áº¡i cÃ´ng nghá»‡ thÃ´ng tin ngÃ y nay. Má»™t tá»• chá»©c, má»™t doanh nghiá»‡p, má»™t cÆ¡ quan hay tháº­m chÃ­ má»™t cÃ¡ nhÃ¢n Ä‘á»�u cáº§n má»™t website cho cÃ´ng viá»‡c cá»§a mÃ¬nh. Máº·t khÃ¡c viá»‡c cÃ³ thá»ƒ xÃ¢y dá»±ng má»™t website láº¡i lÃ  má»™t váº¥n Ä‘á»� khÃ´ng Ä‘Æ¡n giáº£n, nÃ³ Ä‘Ã²i há»�i ngÆ°á»�i xÃ¢y dá»±ng pháº£i cÃ³ kiáº¿n thá»©c vá»� thiáº¿t káº¿ vÃ  láº­p trÃ¬nh web.'),
						array('name' => 'Lập trình Joomla 2.5'						, 'image' => 'joomla.jpg'		, 'description' => 'Joomla CMS lÃ  má»™t há»‡ thá»‘ng quáº£n lÃ½ dá»¯ liá»‡u Ä‘Æ°á»£c Ä‘Ã¡nh giÃ¡ ráº¥t cao hiá»‡n nay, Joomla ráº¥t dá»… sá»­ dá»¥ng Ä‘á»ƒ xÃ¢y dá»±ng má»™t website vÃ  ráº¥t thÃ¢n thiá»‡n vá»›i ngÆ°á»�i sá»­ dá»¥ng. NhÆ°ng Ä‘á»ƒ láº­p trÃ¬nh táº¡o ra cÃ¡c thÃ nh pháº§n má»Ÿ rá»™ng nhÆ° Component, Module, Plugin, Template... cho nÃ³ thÃ¬ khÃ´ng Ä‘Æ¡n giáº£n má»™t chÃºt nÃ o vÃ¬ cáº¥u trÃºc Joomla CMS khÃ¡ '),
						array('name' => 'Khóa học lập trình jQuery (jQuery Master)'	, 'image' => 'jquery.jpg'		, 'description' => 'Náº¿u nÃ³i Ä‘áº¿n láº­p trÃ¬nh web, chÃºng ta nghÄ© ngay Ä‘áº¿n má»™t ngÃ´n ngá»¯ láº­p trÃ¬nh khÃ´ng thá»ƒ thiáº¿u trong má»™t website Ä‘Ã³ lÃ  Javascript. Javascript giÃºp chÃºng ta thá»±c hiá»‡n nhÆ°ng thao tÃ¡c, hiá»‡u á»©ng mÃ  cÃ¡c ngÃ´n ngá»¯ láº­p web nhÆ° PHP, ASP, JSPâ€¦ khÃ³ mÃ  thá»±c hiá»‡n Ä‘Æ°á»£c.'),
						array('name' => 'Xây dựng webchat với NodeJS'				, 'image' => 'node.jpg'			, 'description' => 'KhÃ³a há»�c jQuery nÃ y cÅ©ng bá»• xung thÃªm cho cÃ¡c báº¡n má»™t Javascript framework khÃ¡c Ä‘Ã³ lÃ  NodeJS qua má»™t vÃ­ dá»¥ thá»±c táº¿ lÃ  á»©ng dá»¥ng Web chat. Vá»›i kiáº¿n thá»©c vÃ  vÃ­ dá»¥ cá»§a NodeJS cÃ¡c báº¡n cÃ³ thá»ƒ dá»… dÃ ng lÃ m pháº§n Chat support trÃªn website cá»§a chÃ­nh mÃ¬nh'),
						array('name' => 'Khóa học lập trình  PHP'					, 'image' => 'php.jpg'			, 'description' => 'PHP Ä‘Ã£ vÃ  Ä‘ang trá»Ÿ thÃ nh má»™t ngÃ´n ngá»¯ láº­p trÃ¬nh phá»• biáº¿n trong cÃ¡c á»©ng dá»¥ng web ngÃ y nay. Vá»›i cÃ¡c Æ°u Ä‘iá»ƒm nhÆ° miá»…n phÃ­, dá»… Ä‘á»�c, thao tÃ¡c tá»‘t vá»›i cÃ¡c há»‡ quáº£n trá»‹ cÆ¡ sá»Ÿ dá»¯ liá»‡u, cá»™ng Ä‘á»“ng sá»­ dá»¥ng rá»™ng rÃ£i, thÆ° viá»‡n phong phÃº ... PHP ngÃ y cÃ ng phÃ¡t triá»ƒn vÃ  viá»‡c há»�c PHP Ä‘Ã£ trá»Ÿ nÃªn Ä‘áº·c biá»‡t cáº§n thiáº¿t Ä‘á»‘i vá»›i báº¥t ká»³ láº­p trÃ¬nh '),
						array('name' => 'Khóa học lập trình  Wordpress'				, 'image' => 'wordpress.jpg'	, 'description' => 'WordPress lÃ  má»™t mÃ£ nguá»“n web má»Ÿ Ä‘á»ƒ quáº£n trá»‹ ná»™i dung (CMS â€“ Content Management System ) vÃ  cÅ©ng lÃ  má»™t ná»�n táº£ng blog (Blog Platform) Ä‘Æ°á»£c viáº¿t trÃªn ngÃ´n ngá»¯ PHP sá»­ dá»¥ng há»‡ quáº£n trá»‹ cÆ¡ sá»Ÿ dá»¯ liá»‡u MySQL Ä‘Æ°á»£c phÃ¡t hÃ nh Ä‘áº§u tiÃªn vÃ o ngÃ y 27/5/2003 bá»Ÿi Matt Mullenweg vÃ  Mike Little.'),
						array('name' => 'Khóa học lập trình  Zend Framework 1.X'		, 'image' => 'zend.jpg'			, 'description' => 'Zend Framework lÃ  má»™t thÆ° viá»‡n cÃ¡c lá»›p Ä‘Æ°á»£c xÃ¢y dá»±ng trÃªn ná»�n táº£ng ngÃ´n ngá»¯ PHP, theo hÆ°á»›ng OOP vÃ  Ä‘Æ°á»£c cÃ´ng ty Zend phÃ¡t triá»ƒn. Zend Framework Ä‘Æ°á»£c Ä‘á»‹nh hÆ°á»›ng theo mÃ´ hÃ¬nh MVC vÃ  lÃ  má»™t PHP framework ra Ä‘á»�i khÃ¡ trá»…, chÃ­nh vÃ¬ váº­y ZF Ä‘Ã£ thá»«a hÆ°á»Ÿng nhá»¯ng tinh hoa cá»§a cÃ¡c framework khÃ¡c vÃ  trÃ¡nh khá»�i nhá»¯ng sai '),
				);
        return $courseData;
    }
    function getElement($arrayData, $position,$totalItems){
        $data = array_slice($arrayData, $position,$totalItems);
        return $data;
    }
    $tmp = getElement(createData(), 0, 5);
    